# Generated by Django 4.1.7 on 2023-04-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcreate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCreate',
        ),
    ]
